-- consulta entre fechas vencimientos de contratos de un solicitante

SELECT 
    S.APE1_SOL || ' ' || S.APE2_SOL || ', ' || S.NOM_SOL AS CONTRATADO,
    CT.REF_CONTRATO AS CONTRATO, 
    CT.F_FIN AS FIN,
    P.ORGANICA AS ORGANICA
FROM SOLICITANTE S
INNER JOIN CONTRATOS CT ON CT.CONTRATADO = S.DNI_SOL
INNER JOIN CONVOCATORIA CV ON CV.REFERENCIA = CT.CONVOCATORIA
INNER JOIN PROYECTO P ON P.ORGANICA = CV.REF_PROY
WHERE CT.F_FIN BETWEEN TO_DATE(:P17_FDESDE, 'DD/MM/YYYY') AND TO_DATE(:P17_FHASTA, 'DD/MM/YYYY')