SELECT 
    S.APE1_SOL || ' ' || S.APE2_SOL || ', ' || S.NOM_SOL AS CONTRATADO,
    CT.REF_CONTRATO AS CONTRATO, 
    CT.F_INI AS INICIO, 
    CT.F_FIN AS FIN,
    CV.REFERENCIA AS REF_CONV,  
    P.ORGANICA AS ORGANICA, 
    P.FECHA_INI AS INI_PROY, 
    P.FECHA_FIN AS FIN_PROY
FROM SOLICITANTE S
INNER JOIN CONTRATOS CT ON CT.CONTRATADO = S.DNI_SOL
INNER JOIN CONVOCATORIA CV ON CV.REFERENCIA = CT.CONVOCATORIA
INNER JOIN PROYECTO P ON P.ORGANICA = CV.REF_PROY
