SELECT C.REFERENCIA,
       C.TITULO,
       C.TIT_REQUERIDA,
       CASE C.ABIERTO WHEN 1 THEN 'Sí' ELSE 'No' END AS ABIERTO,
       R.APE1 || ' ' || R.APE2 || ', ' || R.NOMBRE AS INVESTIGADOR,
       C.REF_PROY,
       C.NUM_PLAZAS
  FROM CONVOCATORIA C
  LEFT JOIN RESPONSABLE R ON C.REF_INV = R.DNI

-- creación de trigger para generar ref

CREATE OR REPLACE TRIGGER TRG_CONVOCATORIA_REF
BEFORE INSERT ON CONVOCATORIA
FOR EACH ROW
WHEN (NEW.REFERENCIA IS NULL)
BEGIN
  :NEW.REFERENCIA := 'CONVO' || LPAD(SEQ_CONVOCATORIA_REF.NEXTVAL, 2, '0');
END;
/

-- para qeu en la creacion muestre ip

SELECT APE1 || ' ' || APE2 || ', ' || NOMBRE AS DISPLAY_VALUE, DNI AS RETURN_VALUE
FROM RESPONSABLE
ORDER BY APE1, APE2

-- para que una vez seleccionado el ip, solo muestre sus proyectos
-- necesario activar "Cascading list of values"

SELECT P.TITULO, P.ORGANICA
FROM PROYECTO P
WHERE P.RESPONSABLE = :P9_REF_INV
ORDER BY P.TITULO;