name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Mejora la relevancia del análisis en SonarCloud

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar presencia de SONAR_TOKEN
        run: |
          if ($env:SONAR_TOKEN -eq $null -or $env:SONAR_TOKEN -eq "") {
            Write-Host "SONAR_TOKEN NO está disponible en este contexto"
            exit 1
          } else {
            Write-Host "SONAR_TOKEN está presente"
          }
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Limpiar caché SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-cache-${{ github.run_id }}
          restore-keys: |
            sonar-cache-

      - name: Ejecutar análisis con SonarQube
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.organization=far0010tfg
            -Dsonar.projectKey=far0010_TFGUBU-Fran_Arroyo
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
