name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Mejora la relevancia del análisis en SonarCloud

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar presencia de SONAR_TOKEN
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
            echo "SONAR_TOKEN NO está disponible en este contexto"
            exit 1
          else
            echo "SONAR_TOKEN está presente"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Limpiar caché SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-cache-${{ github.run_id }}
          restore-keys: |
            sonar-cache-

      - name: Ejecutar análisis con SonarQube
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.organization=<far0010TFG>
            -Dsonar.projectKey=<far0010tfg>
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

