name: Publicar informe Allure

on:
  push:
    branches:
      - main
    paths:
      - 'projects-docs/allure-report/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Copia el informe a carpeta temporal
        run: |
          mkdir sitio
          cp -r projects-docs/allure-report/* sitio/

      - name: Publica en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sitio
