name: Publicar informe Allure

on:
  push:
    branches: [main]
    paths:
      - 'projects-docs/allure-report/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Preparar carpeta para publicar
        run: |
          rm -rf sitio
          mkdir -p sitio/informe
          cp -a projects-docs/allure-report/. sitio/informe/

      - name: Publicar solo el informe Allure
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sitio
          keep_files: false
